apiVersion: v1
kind: Secret
metadata:
  name: projectplutonium-secrets
  namespace: projectplutonium-dev
type: Opaque
stringData:
  POSTGRES_USER: plutonium_user
  POSTGRES_PASSWORD: secure_password_change_me
  POSTGRES_DB: projectplutonium
